package paser.xpath2;
/* Generated By:JJTree: Do not edit this line. xpath-src\XPathTreeConstants.java */

public interface XPathTreeConstants
{
  public int JJTXPATH2 = 0;
  public int JJTXPATH = 1;
  public int JJTEXPR = 2;
  public int JJTVOID = 3;
  public int JJTFOREXPR = 4;
  public int JJTQUANTIFIEDEXPR = 5;
  public int JJTIFEXPR = 6;
  public int JJTOREXPR = 7;
  public int JJTANDEXPR = 8;
  public int JJTCOMPARISONEXPR = 9;
  public int JJTRANGEEXPR = 10;
  public int JJTADDITIVEEXPR = 11;
  public int JJTMULTIPLICATIVEEXPR = 12;
  public int JJTUNIONEXPR = 13;
  public int JJTINTERSECTEXCEPTEXPR = 14;
  public int JJTINSTANCEOFEXPR = 15;
  public int JJTTREATEXPR = 16;
  public int JJTCASTABLEEXPR = 17;
  public int JJTCASTEXPR = 18;
  public int JJTUNARYEXPR = 19;
  public int JJTMINUS = 20;
  public int JJTPLUS = 21;
  public int JJTPATHEXPR = 22;
  public int JJTSLASH = 23;
  public int JJTSLASHSLASH = 24;
  public int JJTSTEPEXPR = 25;
  public int JJTFORWARDAXIS = 26;
  public int JJTABBREVFORWARDSTEP = 27;
  public int JJTREVERSEAXIS = 28;
  public int JJTABBREVREVERSESTEP = 29;
  public int JJTNODETEST = 30;
  public int JJTNAMETEST = 31;
  public int JJTWILDCARD = 32;
  public int JJTNCNAMECOLONSTAR = 33;
  public int JJTSTARCOLONNCNAME = 34;
  public int JJTPREDICATELIST = 35;
  public int JJTPREDICATE = 36;
  public int JJTSTRINGLITERAL = 37;
  public int JJTINTEGERLITERAL = 38;
  public int JJTDECIMALLITERAL = 39;
  public int JJTDOUBLELITERAL = 40;
  public int JJTVARNAME = 41;
  public int JJTPARENTHESIZEDEXPR = 42;
  public int JJTCONTEXTITEMEXPR = 43;
  public int JJTFUNCTIONCALL = 44;
  public int JJTSINGLETYPE = 45;
  public int JJTSEQUENCETYPE = 46;
  public int JJTOCCURRENCEINDICATOR = 47;
  public int JJTITEMTYPE = 48;
  public int JJTATOMICTYPE = 49;
  public int JJTANYKINDTEST = 50;
  public int JJTDOCUMENTTEST = 51;
  public int JJTTEXTTEST = 52;
  public int JJTCOMMENTTEST = 53;
  public int JJTPITEST = 54;
  public int JJTATTRIBUTETEST = 55;
  public int JJTATTRIBNAMEORWILDCARD = 56;
  public int JJTSCHEMAATTRIBUTETEST = 57;
  public int JJTATTRIBUTEDECLARATION = 58;
  public int JJTELEMENTTEST = 59;
  public int JJTELEMENTNAMEORWILDCARD = 60;
  public int JJTSCHEMAELEMENTTEST = 61;
  public int JJTELEMENTDECLARATION = 62;
  public int JJTATTRIBUTENAME = 63;
  public int JJTELEMENTNAME = 64;
  public int JJTTYPENAME = 65;
  public int JJTPATTERN = 66;
  public int JJTPATHPATTERN = 67;
  public int JJTPATTERNSTEP = 68;
  public int JJTPATTERNAXIS = 69;
  public int JJTNCNAME = 70;
  public int JJTQNAME = 71;
  public int JJTFUNCTIONQNAME = 72;


  public String[] jjtNodeName = {
    "XPath2",
    "XPath",
    "Expr",
    "void",
    "ForExpr",
    "QuantifiedExpr",
    "IfExpr",
    "OrExpr",
    "AndExpr",
    "ComparisonExpr",
    "RangeExpr",
    "AdditiveExpr",
    "MultiplicativeExpr",
    "UnionExpr",
    "IntersectExceptExpr",
    "InstanceofExpr",
    "TreatExpr",
    "CastableExpr",
    "CastExpr",
    "UnaryExpr",
    "Minus",
    "Plus",
    "PathExpr",
    "Slash",
    "SlashSlash",
    "StepExpr",
    "ForwardAxis",
    "AbbrevForwardStep",
    "ReverseAxis",
    "AbbrevReverseStep",
    "NodeTest",
    "NameTest",
    "Wildcard",
    "NCNameColonStar",
    "StarColonNCName",
    "PredicateList",
    "Predicate",
    "StringLiteral",
    "IntegerLiteral",
    "DecimalLiteral",
    "DoubleLiteral",
    "VarName",
    "ParenthesizedExpr",
    "ContextItemExpr",
    "FunctionCall",
    "SingleType",
    "SequenceType",
    "OccurrenceIndicator",
    "ItemType",
    "AtomicType",
    "AnyKindTest",
    "DocumentTest",
    "TextTest",
    "CommentTest",
    "PITest",
    "AttributeTest",
    "AttribNameOrWildcard",
    "SchemaAttributeTest",
    "AttributeDeclaration",
    "ElementTest",
    "ElementNameOrWildcard",
    "SchemaElementTest",
    "ElementDeclaration",
    "AttributeName",
    "ElementName",
    "TypeName",
    "Pattern",
    "PathPattern",
    "PatternStep",
    "PatternAxis",
    "NCName",
    "QName",
    "FunctionQName",
  };
}
